[build]
  command = """
    echo "Starting build process" && \
    npm run build || (echo "React build failed" && exit 1) && \
    echo "React build successful, installing function dependencies" && \
    cd netlify/functions && npm install || (echo "Function dependency installation failed" && exit 1) && \
    echo "Build process completed successfully"
  """
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.0.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
