[build]
  command = """
    echo "Starting build process" && \
    npm run build > build.log 2>&1 || (cat build.log && echo "React build failed" && exit 1) && \
    echo "React build successful, installing function dependencies" && \
    (cd netlify/functions && npm install > function-install.log 2>&1) || (cat function-install.log && echo "Function dependency installation failed" && exit 1) && \
    echo "Build process completed successfully"
  """
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.0.0"
  REACT_APP_FIREBASE_API_KEY = "AIzaSyBI_K1aSiful-dW-sFX6Fx5Bu5V-3gl1w8"
  REACT_APP_FIREBASE_AUTH_DOMAIN = "wild-recipes-fa59a.firebaseapp.com"
  REACT_APP_FIREBASE_PROJECT_ID = "wild-recipes-fa59a"
  REACT_APP_FIREBASE_STORAGE_BUCKET = "wild-recipes-fa59a.appspot.com"
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID = "371001502696"
  REACT_APP_FIREBASE_APP_ID = "1:371001502696:web:fb8705effe697fdf4cd25d"
  REACT_APP_FIREBASE_MEASUREMENT_ID = "G-02G9MCFGEZ"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
