[build]
  command = "npm run build && cd netlify/functions && npm install"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.0.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
