[build]
  command = """
    echo "Starting build process" && \
    npm run build > build.log 2>&1 || (cat build.log && echo "React build failed" && exit 1) && \
    echo "React build successful, installing function dependencies" && \
    (cd netlify/functions && npm install > function-install.log 2>&1) || (cat function-install.log && echo "Function dependency installation failed" && exit 1) && \
    echo "Build process completed successfully"
  """
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.0.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
